export { resolveEyeExpression } from './expression'
export type { ExpressionModel, EyeExpression } from './expression'
export { canFitEyesInCanvas, clampGaze, gazeLimits, minimumCanvasSize } from './gaze'
export type { CanvasMinimumSize, GazeLimits, NumericRange } from './gaze'
export type { EyeGeometry, EyeModel, Point } from './eye'
export type { CanvasModel, ColorModel, FaceModel } from './face'
